volumes:
  qdrant_data:
  watcher_state:
  huggingface_cache:

services:
  # Qdrant vector database - the heart of semantic search
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: claude-reflection-qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    mem_limit: ${QDRANT_MEMORY:-1g}
    memswap_limit: ${QDRANT_MEMORY:-1g}

  # Continuous watcher service (optional)
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    container_name: claude-reflection-watcher
    depends_on:
      - qdrant
    volumes:
      - ${CLAUDE_LOGS_PATH:-~/.claude/projects}:/logs:ro
      - ./scripts:/scripts:ro
      - watcher_state:/app/state
    environment:
      - QDRANT_URL=http://qdrant:6333
      - LOGS_DIR=/logs
      - STATE_FILE=/app/state/watcher-state.json
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      # Main settings
      - IMPORT_INTERVAL=${IMPORT_INTERVAL:-${WATCH_INTERVAL:-60}}
      - BATCH_SIZE=${BATCH_SIZE:-100}
      - CHUNK_SIZE=${CHUNK_SIZE:-10}
      # Behavior settings
      - FORCE_FULL_CHECK_INTERVAL=${FORCE_FULL_CHECK_INTERVAL:-3600}
      - QUICK_CHECK_ONLY=${QUICK_CHECK_ONLY:-false}
      # Performance settings
      - MAX_PARALLEL_HASHES=${MAX_PARALLEL_HASHES:-5}
      # Logging settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_STATS_EVERY=${LOG_STATS_EVERY:-10}
      - VERBOSE_CHECKS=${VERBOSE_CHECKS:-false}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    profiles: ["watch"]
    mem_limit: 2g
    memswap_limit: 2g

  # MCP server for Claude integration
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-server
    container_name: claude-reflection-mcp
    depends_on:
      - qdrant
    volumes:
      - huggingface_cache:/home/mcpuser/.cache/huggingface
    environment:
      - QDRANT_URL=http://qdrant:6333
      - ENABLE_MEMORY_DECAY=${ENABLE_MEMORY_DECAY:-true}
      - DECAY_WEIGHT=${DECAY_WEIGHT:-0.3}
      - DECAY_SCALE_DAYS=${DECAY_SCALE_DAYS:-90}
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/home/mcpuser/.cache/huggingface
      - HF_HOME=/home/mcpuser/.cache/huggingface
      - MODEL_CACHE_DAYS=${MODEL_CACHE_DAYS:-7}
    restart: unless-stopped
    stdin_open: true
    tty: false
    profiles: ["mcp"]

networks:
  default:
    name: claude-reflection-network
    external: false