volumes:
  qdrant_data:
  mcp_model_cache:

services:
  # Qdrant vector database - the heart of semantic search
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: claude-reflection-qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    mem_limit: ${QDRANT_MEMORY:-1g}
    memswap_limit: ${QDRANT_MEMORY:-1g}

  # MCP server for Claude integration
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-server
    container_name: claude-reflection-mcp
    depends_on:
      - qdrant
    volumes:
      - mcp_model_cache:/home/mcpuser/.cache/huggingface
      - ./mcp-server/src:/app/src:ro
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2}
      - VECTOR_SIZE=${VECTOR_SIZE:-384}
      - ENABLE_MEMORY_DECAY=${ENABLE_MEMORY_DECAY:-true}
      - DECAY_WEIGHT=${DECAY_WEIGHT:-0.3}
      - DECAY_SCALE_DAYS=${DECAY_SCALE_DAYS:-90}
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/home/mcpuser/.cache/huggingface
      - MODEL_CACHE_DAYS=${MODEL_CACHE_DAYS:-7}
    restart: unless-stopped
    stdin_open: true
    tty: false

networks:
  default:
    name: claude-reflection-network
    external: false